name: Auto docs_github_pages arita37.github.io/myutil/en/zdocs_y23487teg65f6/
 
### target page :  https://arita37.github.io/myutil/en/zdocs_y23487teg65f6/utilmy.html#module-utilmy.cli


on:
  workflow_dispatch:
    inputs:  
    
#  schedule:
#    - cron:  '0 14 * * *'      #### 60mins
#    #    - cron:  '*/10 * * * *'

  push:
    branches:
    - zdocs_y23487teg65f6



jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    #- uses: actions/checkout@v1
    #  ref: ${{ github.head_ref }
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        
    - name: Set up Python 3.7.*
      uses: actions/setup-python@v1
      with:
        python-version: 3.7.*
      
    - name: Install pipenv
      uses: dschep/install-pipenv-action@v1
      
  
    - name: Cache pipenv virtualenv
      id: cache-pipenv
      uses: actions/cache@v1
      with:
        path: /opt/hostedtoolcache/Python/
        key: ${{ runner.os }}-pipenv-${{ hashFiles('**py36_docfull.txt') }}
          

    #- name: Install numpy
    #  if: steps.cache-pipenv.outputs.cache-hit != 'true'
    #  run: pip install numpy==1.18.2   pillow==6.2.1  scipy
      

    - name: Install repo requirements  1
      if: steps.cache-pipenv.outputs.cache-hit != 'true'
      run: |
           pip install -r  py36_min.txt


    - name: Install repo requirements   2
      if: steps.cache-pipenv.outputs.cache-hit != 'true'
      run:  |
        ls .
        pip install -r  py36_docfull.txt
        pip install protobuf==3.16.0
        pip install onnx
        #pip install -r install/requirements_fake.txt


    - name: Install utilmy
      run:  |
        pip install -e .
        python -c "import utilmy"

           

    - name: test_import
      run: |
           python -c "import os, pandas as pd; print(os)"
           python -c "import utilmy"        
           pip install -U sphinx  sphinx-rtd-theme  GitPython  rinohtype pygments
           pip install -r  py36_sphynxdoc.txt
        

    ################################################################################
    #- name: Prereqs
    #  env:
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #  #run: |
    #  #  apt-get update
    #  #  apt-get install -y git

    - name: Execute script to build our documentation and update pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        chmod -R 777 docs_ghpage
        docs_ghpage/buildDocs.sh
      shell: bash


