name: Auto-Doc in docs/doc_index.py

###  https://github.com/arita37/awesome-actions#static-analysis

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  workflow_dispatch:
    inputs:  

#  push:
#    branches:
#    - main

  schedule:
    - cron:  '0 0 * * 0'    
    # - cron:  '0 2 * * *'      #### 60mins
    #    - cron:  '*/10 * * * *'


#  pull_request:
#    branches:
#    - main

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    #- uses: actions/checkout@v1
    #  ref: ${{ github.head_ref }
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        
    - name: Set up Python 3.7.*
      uses: actions/setup-python@v1
      with:
        python-version: 3.7.*
      
    - name: Install pipenv
      uses: dschep/install-pipenv-action@v1
      
  
    - name: Cache pipenv virtualenv
      id: cache-pipenv
      uses: actions/cache@v1
      with:
        path: /opt/hostedtoolcache/Python/
        key: ${{ runner.os }}-pipenv-${{ hashFiles('**py36_docfull.txt') }}
          

    #- name: Install numpy
    #  if: steps.cache-pipenv.outputs.cache-hit != 'true'
    #  run: pip install numpy==1.18.2   pillow==6.2.1  scipy
      

    - name: Install repo requirements  1
      if: steps.cache-pipenv.outputs.cache-hit != 'true'
      run: |
           pip install -r  py36_min.txt


    - name: Install repo requirements   2
      if: steps.cache-pipenv.outputs.cache-hit != 'true'
      run:  |
        ls .
        pip install -r  py36_docfull.txt


    - name: Install utilmy
      run:  |
        pip install -e .
        python -c "import utilmy"

           



    - name: test_import
      run: |
           python -c "import os, pandas as pd; print(os)"
           python -c "import utilmy"        
        

    - name: Code Syntax Checker flake8
      continue-on-error: true
      run:  |
        pip install --upgrade flake8
        flake8  --statistics   --count    --max-line-length 140   2>&1 | tee -a docs/flake8_syntax_error.py  
        
        

    ########  Runs All test  ######################################
    - name: test_setup
      run: |
          mkdir -p    /home/runner/work/log_tmp/
          chmod -R 777 . 

          

    ########  Generate Docs     
    - name: docs_generate
      continue-on-error: true
      run: |
           docs all      --repo_dir utilmy/  --dirout docs/
           rm -rf docs/doc_main.md
           rm -rf docs/output_repo.csv
           pip freeze > docs/piplist.txt


    - name: Auto-Commit
      continue-on-error: true
      id: auto_commmit
      uses: stefanzweifel/git-auto-commit-action@v4.8.0
      with:
          # Optional, but recommended
          # Defaults to "Apply automatic changes"
          commit_message: Auto Docs

          # Optional branch name where commit should be pushed to.
          # Defaults to the current branch.
          # branch: main

          # Optional. Used by `git-commit`.
          # See https://git-scm.com/docs/git-commit#_options
          commit_options: '--no-verify --signoff'

          # Optional glob pattern of files which should be added to the commit
          file_pattern: docs/*.* 

          # Optional local file path to the repository
          # Defaults to the root of the repository
          repository: .
