name: AA_Build and Publish Package PyPI

###  https://github.com/arita37/awesome-actions#static-analysis

on:
  workflow_dispatch:
    inputs:  
    
  push:
    branches:
    - main

#  pull_request:
#    branches:
#    - main

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true



jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    #- uses: actions/checkout@v1
    #  ref: ${{ github.head_ref }
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        
    - name: Set up Python 3.7.*
      uses: actions/setup-python@v1
      with:
        python-version: 3.7.*
      
    - name: Install pipenv
      uses: dschep/install-pipenv-action@v1
      
  
    - name: Cache pipenv virtualenv
      id: cache-pipenv
      uses: actions/cache@v1
      with:
        path: /opt/hostedtoolcache/Python/
        key: ${{ runner.os }}-pipenv-${{ hashFiles('**py36.txt') }}
          

    #- name: Install numpy
    #  if: steps.cache-pipenv.outputs.cache-hit != 'true'
    #  run: pip install numpy==1.18.2   pillow==6.2.1  scipy
      

    - name: Install repo requirements  1
      if: steps.cache-pipenv.outputs.cache-hit != 'true'
      run: |
           pip install -r  py36_min.txt


    - name: Install repo requirements   2
      if: steps.cache-pipenv.outputs.cache-hit != 'true'
      run:  |
        ls .
        pip install -r  py36.txt
        #pip install -r install/requirements_fake.txt


    - name: Install utilmy
      run:  |
        pip install -e .
        python -c "import utilmy"



    - name: test_import
      run: |
           python -c "import os, pandas as pd; print(os)"
           python -c "import utilmy"        
        

    - name: Code Syntax Checker flake8
      continue-on-error: true
      run:  |
        pip install --upgrade flake8
        flake8  --statistics   --count    --max-line-length 140   2>&1 | tee -a docs/flake8_syntax_error.py  
        
        

    ########  Runs All test  ######################################
    - name: test_setup
      run: |
          mkdir -p    /home/runner/work/log_tmp/
          chmod -R 777 . 


    ################################################################
    - name: test_cli
      continue-on-error: true
      run: |
          python utilmy/cli.py help


    - name: test_images
      continue-on-error: true    
      run: |
          python test.py test_images

    - name: test_deeplearning
      continue-on-error: true    
      run: |
          python test.py test_deeplearning_torch

    - name: test_recsys  
      continue-on-error: true
      run:  python test.py   test_recsys

    - name: test_ppandas
      run: python test.py test_ppandas
    
    
    - name: test_docs_cli 
      run: python test.py test_docs_cli
    
    - name: test_nlp
      run: python test.py test_nlp

    - name: test_distributed
      continue-on-error: true  
      run: ls . 
      # python test.py test_distributed

    

    - name: test_oos 
      run: python test.py test_oos

    - name: test_utils
      run: python test.py test_utils
      
    - name: test_tabular
      run: python test.py test_tabular

    - name: test_adatasets
      run: python test.py test_adatasets

    - name: test_nnumpy 
      run: python test.py test_nnumpy

    - name: test_dates
      run: python test.py test_dates

    - name: test_decorators 
      run: python test.py test_decorators

    - name: test_utilmy
      run: python test.py test_utilmy

    - name: test_viz_vizhtml
      run:  python test.py   test_viz_vizhtml

    - name: test_parallel  
      run:  python test.py   test_parallel








################# This Job will upload a Python Package using Twine when a release is created
  deploy:
    needs : [build] # List of dependent Jobs 
    if: success()   # check if all previous (needs) dependent jobs were successfull  then only execute
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'


    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine

    - name: Build and publish
      #env:
      #  TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
      #  TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        # echo "$TWINE_USERNAME"
        python run_pipy.py
        python setup.py sdist bdist_wheel
        twine upload dist/*  --username ${{ secrets.PYPI_USERNAME }}     --password ${{ secrets.PYPI_PASSWORD }}  --skip-existing   --repository-url https://upload.pypi.org/legacy/  --verbose   
