name: load_use_docker

on:
  workflow_dispatch:
    inputs:  

    
  push:
    branches:
      - master


jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      #- name: Build and push
      #  id: docker_build
      #  uses: docker/build-push-action@v2
      #  with:
      #    push: true
      #    tags: artia37/centos:7.2


  python-test:
    runs-on: ubuntu-latest
    needs: docker-build
    container: 
      image: artia37/centos:7.2
      options: --user root
    steps:
      - uses: actions/checkout@v2
      - run: |
          python -c 'import os; print(os)'



