name: Docker Run test


#### Build Command :     https://github.com/arita37/myutil/actions/workflows/docker_build_zdocker1.yml

#### Docker definiton:     https://github.com/arita37/myutil/tree/zdocker2/dockers

##### Publish Registry:     https://hub.docker.com/u/artia37



on:
  workflow_dispatch:
    inputs:  

#  push:
#    branches:
#      - zdocker1


jobs:

  #####################################################################################################################
  #####################################################################################################################
  # ### Build (local)
  # ````
  # docker build -t local/docker-google-drive:v1 -f Dockerfile .

  # ### Usage
  # docker run -d \
  # -e CLIENT_ID='my-client-id' \
  # -e CLIENT_SECRET='my-client-secret' \
  # -e LAST_ACCESS_TOKEN='my-last-access-token' \
  # -e REFRESH_TOKEN='my-refresh-token' \
  # --security-opt apparmor:unconfined \
  # --cap-add mknod \
  # --cap-add sys_admin \
  # --device=/dev/fuse \
  # -v /mnt/drive:/mnt/gdrive:shared \
  # artia37/docker-google-drive:v1
  # ````

  # ### Structure
  # * `/mnt/gdrive`: Google Drive Fuse mount directory inside container

  docker-ubuntu-googledrive-build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        run: |
          cd dockers/docker-google-drive
          docker buildx build -f ./Dockerfile --tag artia37/ubuntu-google-drive:v1 --push .


  docker-ubuntu-googledrive-runtest:
    runs-on: ubuntu-latest
    needs: docker-ubuntu-googledrive-build
    container: 
      image: artia37/ubuntu-google-drive:v1
      env:
        # Steps
        # 1) CLIENT_ID and CLIENT_SECRET are google oAuth client ID & client secret
        #     Follow this guide to get those values
        #     https://github.com/astrada/google-drive-ocamlfuse/wiki/Headless-Usage-&-Authorization
        #
        # 
        # 2) Then run:    google-drive-ocamlfuse -id <CLIENT_ID> -secret <CLIENT_SECRET>
        #     A browser will be started pointing to an authorization page, and when you allow access to Google Drive, 
        #     a verification code will be generated, called :
        # 
        #
        # 3) Copy this verification code and paste it in the console where the application is running.
        #    application will notify you that it has retrieved the tokens from Google.
        #   
        #     LAST_ACCESS_TOKEN & REFRESH_TOKEN are generated automate whenever you re-run authorization
        #     Those values are saved in ~/.gdfuse/default/state
        #     Please copy manuall from there   ~/.gdfuse/default/state

        CLIENT_ID:         ${{ secrets.GDRIVER_API_CLIENT_ID }}
        CLIENT_SECRET:     ${{ secrets.GDRIVER_API_CLIENT_SECRET }}
        LAST_ACCESS_TOKEN: ${{ secrets.GDRIVER_API_LAST_ACCESS_TOKEN }}
        REFRESH_TOKEN:     ${{ secrets.GDRIVER_API_REFRESH_TOKEN }}
      options: 
        - --user root
        - --security-opt apparmor:unconfined
        - --cap-add mknod
        - --cap-add sys_admin
        - --device=/dev/fuse

    steps:
      - uses: actions/checkout@v2
      - run: |
          ls .  && pwd && whoami
          ls -l /mnt/gdrive



