name: Docker Run test


#### Build Command :     https://github.com/arita37/myutil/actions/workflows/docker_build_zdocker1.yml

#### Docker definiton:     https://github.com/arita37/myutil/tree/zdocker2/dockers

##### Publish Registry:     https://hub.docker.com/u/artia37



on:
  workflow_dispatch:
    inputs:  

#  push:
#    branches:
#      - zdocker1


jobs:

  docker-googledrive:
    runs-on: ubuntu-latest
    needs: docker-build
    container: 
      image: artia37/centos-google-drive:v1 
      options: --user root
    steps:
      - uses: actions/checkout@v2
      - run: |
          ls .  && pwd && whoami

  docker-ubuntu-googledrive-build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        run: |
          cd dockers/docker-google-drive
          docker buildx build -f ./Dockerfile --tag artia37/ubuntu-google-drive:v1 --push .

  docker-ubuntu-googledrive-runtest:
    runs-on: ubuntu-latest
    needs: docker-ubuntu-googledrive-build
    container: 
      image: artia37/ubuntu-google-drive:v1
      env:
        
        ### How to get this token
        CLIENT_ID: ${{ secrets.GDRIVER_API_CLIENT_ID }}
        

        CLIENT_SECRET: ${{ secrets.GDRIVER_API_CLIENT_SECRET }}
        

        LAST_ACCESS_TOKEN: ${{ secrets.GDRIVER_API_LAST_ACCESS_TOKEN }}
        
        
        REFRESH_TOKEN: ${{ secrets.GDRIVER_API_REFRESH_TOKEN }}



      options: 
        - --user root
        - --security-opt apparmor:unconfined
        - --cap-add mknod
        - --cap-add sys_admin
        - --device=/dev/fuse

    steps:
      - uses: actions/checkout@v2
      - run: |
          ls .  && pwd && whoami
          ls -l /mnt/gdrive

