name: Spark_run

on:
  push:
    branches:
      - spark
      - spark2

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Start containers
        run: docker-compose up -d --build -f dockers/spark/docker-compose.yml



      - name: Full Run
        # continue-on-error: true
        run: docker-compose exec -T spark python utilmy/spark/main.py  --config_path  utilmy/spark/config/config.yaml       



      - name: Stop containers
        if: always()

        run: docker-compose down
